config/routes.rb
Rails.application.routes.draw do
  resources :teams, :except => [:new, :edit]

  resources :clubs, :except => [:new, :edit]

end

app/models/club.rb
class Club < ActiveRecord::Base
	has_many :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def render_with_protection(json_content, parameters = {})
    render parameters.merge(content_type: 'application/json', text: ")]}',\n" + json_content)
  end

protected

  def verified_request?
    super || form_authenticity_token == request.headers['X_XSRF_TOKEN']
  end  
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :update, :destroy]

  before_filter :intercept_html_requests
  layout false
  respond_to :json

  # GET /clubs.json
  def index
    @clubs = Club.all

    render_with_protection @clubs.to_json
  end

  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])

    render_with_protection @club.to_json
  end

  # POST /clubs.json
  def create
    @club = Club.new(club_params)

    if @club.save
      render_with_protection @club.to_json, {status: :created, location: @club}
    else
      render_with_protection @club.errors.to_json, {status: :unprocessable_entity}
    end
  end

  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    if @club.update_attributes(club_params)
      head :no_content
    else
      render_with_protection @club.errors.to_json, {status: :unprocessable_entity}
    end
  end

  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :contact_officer, :date_created)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :update, :destroy]
  
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  # GET /teams.json
  def index
    @teams = Team.all

    render_with_protection @teams.to_json
  end

  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    render_with_protection @team.to_json
  end

  # POST /teams.json
  def create
    @team = Team.new(team_params)

    if @team.save
      render_with_protection @team.to_json, {status: :created, location: @team}
    else
      render_with_protection @team.errors.to_json, {status: :unprocessable_entity}
    end
  end

  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    if @team.update_attributes(team_params)
      head :no_content
    else
      render_with_protection @team.errors.to_json, {status: :unprocessable_entity}
    end
  end

  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:club_id, :name, :captain, :date_created)
    end

    def intercept_html_requests
      redirect_to('/') if request.format == Mime::HTML
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_officer %><br>
    <%= f.text_field :contact_officer %>
  </div>
  <div class="field">
    <%= f.label :date_created %><br>
    <%= f.datetime_select :date_created %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact officer</th>
      <th>Date created</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.contact_officer %></td>
        <td><%= club.date_created %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>Contact officer:</strong>
  <%= @club.contact_officer %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @club.date_created %>
</p>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueTutorial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>